#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
blue = '#5faae8'
red = '#d0666f'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'agnoster_short'
      folder_icon = ''

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    template = ' on <p:red>{{ .HEAD }}</><p:blue>{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}</> <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true
 
[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'yellow'
    template = '{{ if .Error }}{{ .Error }}{{ else }}󰌠 {{ .Full }}{{ end }} <p:blue>({{ if .Venv }}{{ .Venv }}{{ end }})</>'

  [[blocks.segments]]
    type = 'dart'
    foreground = 'p:blue'
    template = '{{ if .Error }}<p:red>{{ .Error }}</>{{ else }} {{ .Full }}{{ end }}'

  [[blocks.segments]]
    type = 'rust'
    foreground = '#e43716'
    template = '  {{ .Full }} '


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
