target = "/usr/local/bin"
exclude = [
    '^\.git.*$',
    '\.bub\.toml$',
    '^setup_on_arch\..*$',
    '\.unboxrc.*$',
    "^(README|LICEN[CS]E|COPYING).*$",
]
include = []
link_root = false
link_type = "absolute"
